// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpvocdhrzvqekewakfgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhwdm9jZGhyenZxZWtld2FrZmdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjYwODAsImV4cCI6MjA2NjM0MjA4MH0.pUSA3HE6RQYPVL2g1CW18XnCALMLEiEt3IyLy7LsrdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);